### ISSUE TITLE
UI/front end part

### ISSUE THREAD

**Issue by suriyaJaay** [NeverBounce/NeverBounceAPI-PHP#15]
hi,

can you pls provide some UI/front part for this??

Thank you

**Comment by mmollick** [comment]
The purpose of this wrapper is to provide an easy way of integrating our API into your php applications. This is wrapper does not interact with the frontend of your web application at all, so there is no UI components to this.

You may be interested in our Javascript widget that is currently in beta (we'll be releasing it this quarter). It allows you to hook directly to your forms for point of entry verification and provides feedback to the user.
