### ISSUE TITLE
Plus addressing broken in Single Verification

### ISSUE THREAD

**Issue by timwsuqld** [NeverBounce/NeverBounceAPI-PHP#17]
0d5aadb62fcfa0d38761fca3568fe1227aedcda5 in supposed to fix this, but actually appears to break it.

```
php > $data = ['email' => 'email+subaddress@gmail.com'];
php > echo http_build_query($data, null, null, PHP_QUERY_RFC1738);
email=email%2Bsubaddress%40gmail.com
php > echo http_build_query($data, null, null, PHP_QUERY_RFC3986);
email=email%2Bsubaddress%40gmail.com
php > echo http_build_query($data);
email=email%2Bsubaddress%40gmail.com
```

http_build_query (at least in PHP 7, where i'm testing it, but I believe in older PHP anyway) correctly encodes to + symbol. Trying to preencode it makes it worse, because then the % symbol gets encoded by http_build_query. Reverting 0d5aadb62fcfa0d38761fca3568fe1227aedcda5 fixes this issue.

Edit: I've testing in php 5.6 as well now, and http_build_query correctly encodes the + there as well.

**Comment by mmollick** [comment]
Looks like you are correct, http_build_query is handling `+` characters just fine on its own. Thanks for the PR, I'll push this to packagist asap.
