### ISSUE TITLE
Bug in status checker

### ISSUE THREAD

**Issue by drSun** [NeverBounce/NeverBounceAPI-PHP#25]
Hi! There is a bug in NeverBounce\Object\VerificationObject::not() and NeverBounce\Object\VerificationObject::is().

It happens when providing an array as $type. For example, in_array('catchall', [0], false) always returns true.

```
public static $allowed = [
        VerificationObject::VALID,
    ];
...
$checking->is(static::$allowed); // returns true even if result is not VALID
```

**Comment by mmollick** [comment]
I've released a fix in v4.1.4
