### ISSUE TITLE
Important PHP Error in NB_Job class

### ISSUE THREAD

**Issue by luissancho** [NeverBounce/NeverBounceAPI-PHP#3]
Hi.

When trying to bulk verify a list of emails, since you're not sending the Job's "purchased" property in the Retreive response anymore, it raises this: PHP Notice:  Undefined property: stdClass::$purchased in /var/www/miora-dist/releases/1477272277/vendor/neverbounce/neverbounce-php/src/api/NB_Job.php on line 64

Actually, in some servers (depending on config) it behaves as a Fatal Error and stops the execution.

Hope to be helpfull. Regards.

**Comment by mmollick** [comment]
Thanks for the report @luissancho. Looks like we forgot to update the wrapper when it was removed. Running a `composer update` should pull down the latest version.

**Comment by luissancho** [comment]
Composer can't find the new version, maybe it needs to be updated in Packagist first?

**Comment by mmollick** [comment]
Just updated it on Packagist, looks like the auto update isn't working for this repo anymore. Thanks again, let us know if you run into any other issues.

**Comment by luissancho** [comment]
All right! Now it works like charm. Than you very much :)
