### ISSUE TITLE
Minimum PHP (5.5) is very low.

### ISSUE THREAD

**Issue by hopeseekr** [NeverBounce/NeverBounceAPI-PHP#31]
Hi,

The PHP community has uniformly agreed that PHP v7.1 is the current minimum PHP version packages should support. There is some flexibility for supporting v7.0, but the absolute oldest version of PHP that is debatable is v5.6.

This project has a minimum version of 5.5.0. Please consider bumping this to v7.0 or 7.1. At a minimum, 5.6.

**Comment by mmollick** [comment]
Thanks, for the PRs and for giving us a nudge on the PHP version bump. We haven't been collecting PHP versions in our UA string so it's hard to make an informed decision on what versions we *need* to support to support our customers.

I've just pushed out `4.1.6` that will include this information in the UA string for future requests. We'll wait a few weeks to collect enough data before making a decision on which versions to support moving forward.

**Comment by hopeseekr** [comment]
According to W3Techs, [76%+ are 5.6 and newer](https://w3techs.com/technologies/history_details/pl-php), across all installations of PHP. This includes every single "just Wordpress" site that definitely isn't this package's clientele. 

For all potential consumers of your composer.json, as of November 2018, only 2.38% use PHP 5.5, down a whopping 66% from May 2018.  https://blog.packagist.com/php-versions-stats-2018-2-edition/

83.73% of all projects using composer run on PHP 7.0 or higher. And, rumor in my circles is that upwards of *25-33%* of that traffic is due to organizations such as mine testing our packages against 7.0 just for kicks and giggles.

The best part of how composer works is that if you were version break to the currently supported PHP version (7.1), then all of your old releases would still work for people on PHP 5.5. They just wouldn't receive any more fixes, unless you specifically create a v1.0 branch with the current (then old) composer.json in it. Like what I do here: https://github.com/phpexpertsinc/SimpleDTO/tree/v1.0

So, really, there's no need to fear. If you upgraded to 7.1 today, anyone who couldn't use it would automagically be given the latest version they could run.

**Comment by mmollick** [comment]
>The best part of how composer works is that if you were version break to the currently supported PHP version (7.1), then all of your old releases would still work for people on PHP 5.5

That's good to know, I was under the impression changing the minimum version would be a breaking change. In this case I'll go ahead and revive #27 and try to push out an update tomorrow afternoon.
