### ISSUE TITLE
Malformed JSON with \u0000 fails to parse in PHP

### ISSUE THREAD

**Issue by hopeseekr** [NeverBounce/NeverBounceAPI-PHP#34]
Here is the JSON returned by the NeverBounce API PHP client:

```json
{
    "status": "success",
    "result": "valid",
    "flags": [
        "smtp_connectable",
        "has_dns",
        "has_dns_mx"
    ],
    "suggested_correction": "",
    "address_info": {
        "\u0000*\u0000response": {
            "original_email": "test@example.com",
            "normalized_email": "test@example.com",
            "addr": "test",
            "alias": "",
            "host": "example.com",
            "fqdn": "example.com",
            "domain": "example",
            "subdomain": "",
            "tld": "com"
        }
    },
    "credits_info": {
        "\u0000*\u0000response": {
            "paid_credits_used": 0,
            "free_credits_used": 1,
            "paid_credits_remaining": 8917,
            "free_credits_remaining": 872
        }
    },
    "execution_time": 771,
    "email": "test@example.com",
    "result_integer": 0
}
```

The problem is that PHP's `json_decode()` returns `NULL` because `\u0000` is the NUL file terminator byte.

How do we resolve this, short of forking this client and doing a `str_replace()` on the encoded JSON before sending it back out?

**Comment by mmollick** [comment]
Could you give an example of how you got that output? Also could you explain what you're trying to retrieve, are you just looking to get the raw JSON response?

**Comment by mmollick** [comment]
@hopeseekr I'm taking a look into this and it appears these artifacts are being introduced by #30. In this case the `toArray` method is converting the `ResponseObject` contained in `address_info` and `credits_info` directly into an array.

If you're goal is to get the raw JSON string you can use the following after the request:
```
\NeverBounce\ApiClient::getLastRequest()->getRawResponse();
```

**Comment by hopeseekr** [comment]
I'm pretty sure this was on my team's end. i'm sorry.
