### ISSUE TITLE
bug + fix: Could not verify NeverBounce's SSL certificate.  Please make sure that your network is not intercepting certificates

### ISSUE THREAD

**Issue by lordspace** [NeverBounce/NeverBounceAPI-PHP#43]
Hi,

What's the best way to pass the local CA file like these projects?
https://github.com/googleapis/google-api-php-client/issues/788
https://github.com/googleapis/google-api-php-client/issues/1011

I didn't find one so I've patched your code: ApiClient.php, method: request.
I put the following snippet somewhere before: $this->client->execute();
Maybe you can come up with a global static method like the one that sets the API key.
Maybe setDefaultOptions or something.

`
        // Custom fix
        if (getenv('NEVERBOUNCE_CA_FILE')) {
	        $this->client->setOpt( CURLOPT_CAINFO, getenv('NEVERBOUNCE_CA_FILE') );
	        $this->client->setOpt( CURLOPT_CAPATH, getenv('NEVERBOUNCE_CA_FILE') );
        }
`

Usage:
```
// CA cert is from here: https://curl.haxx.se/docs/caextract.html
$ca_file = __DIR__. '/cacert.pem';

```

> OS: Windows 10
>  php -v
> PHP 7.2.22 (cli) (built: Aug 28 2019 09:29:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
>

**Comment by mmollick** [comment]
Hello Svetoslav,

Could provide more details about the error you received? What was the actual error message you received?

Just as a note, we are using Amazon as our certificate issuer. Most up to date applications should trust our certificate out of the box; unless they've been explicitly removed.

**Comment by lordspace** [comment]
Hi,

The error is client side.
See the links I provided

**Comment by mmollick** [comment]
From the links provided it seems like this can be solved by updating your `php.ini` to include `curl.cainfo = "PATH_TO/cacert.pem"`. I'm not sure this needs to be addressed in this library. Is there any reason the configuration update will not work?

**Comment by lordspace** [comment]
Yes, it needs to be addressed in the library. I've provided a solution via
getenv.
Not everyone will have access to php.ini

**Comment by mmollick** [comment]
Fair enough, we should be able to have a team member address this soon.
