### ISSUE TITLE
Bulk feature example steps

### ISSUE THREAD

**Issue by quentint** [NeverBounce/NeverBounceAPI-PHP#9]
The Bulk feature looks awesome, but the API isn't straightforward and the README could use an "Example steps" section.

As the typical bulk process includes multiple steps, I think it would be useful to have a ready-made example scenario here.

What do you think?

ps : creating this issue because I'm discovering the API, and could get the single verification to work in seconds, but still can't figure out how to do batches!

**Comment by mmollick** [comment]
This package hasn't gotten much love as of lately. We're planning to do an overhaul for our wrappers come Q1 after we launch V4 of our API. 

We do have a more thorough explanation of the bulk workflow in our [official docs](https://neverbounce.com/help/api/verifying-a-list/); however not using this wrapper. When we update this package we'll for sure be adding helper methods to make the bulk workflow a breeze. Until then I'll see what I can do about getting an example using the package as is currently.

Thanks for the feedback (and PRs) always good to hear suggestions from the people actually using the package.

**Comment by quentint** [comment]
Thanks for your feedback, and sorry about the PR wave; next time I'll make sure to group them!

**Comment by quentint** [comment]
Still fighting with this... 😠 

Here's what my code looks like:

```php
	public function validateAddresses($addresses) {
		$addresses = array_unique($addresses);
		$s = implode("\n", $addresses);

		$createdBulk = $this->bulkApp->create($s, NB_Bulk::SUPPLIED_DATA);

		/** @var NB_Job $sampleJob */
		$sampleJob = $createdBulk->first();

		$numSleeps = 0;
		$maxSleeps = 10;

		while ($sampleJob->percentage() < 100 && $numSleeps <= $maxSleeps) {
			$numSleeps++;
			sleep(1);
			$sampleJob = $this->bulkApp->retrieve($sampleJob->id)->first();
		}

		if ($sampleJob->percentage() == 100) {
			$results = $this->downloadDataToArray($sampleJob->download());
			return $results;
		} else {
			return false;
		}
	}
```

It may look like it works, but when inputting 5 e-mail addresses, it only `sleep`s once and then considers percentage to be 100%, but when looking at the downloaded data, it only contains 2 (or 3) lines 😞 

Also, the `finished` property never seems to update...

Can you help me with that?

I've already wasted about 50 credits on that! 😢
Don't you offer a demo mode, where credits aren't spent? That'd help a lot.

**Comment by mmollick** [comment]
I just added several examples to the repo in the `examples/` directory, hopefully these help.

Additionally a list of only 5 emails will verify pretty quickly likely within a few seconds. Although the percentage method isn't the best metric for determining if a job is ready for download. You'll want to use the state property instead as the percentage method won't inform you if the job has failed and will not account for any reprocessing the job may need.

You will also want to take a look at the BulkSuppliedData.php example for recommendations on how to actually submit the data. As `\n` doesn't actually get encoded into a newline but rather into the literal characters `\` and `n`.

Currently we don't have a demo mode, it's on our todo list but it's gonna be a little while until we get to it. That's one of the reasons behind the 1000 free API credits. Feel free to shoot an email to `mike` at `neverbounce.com` with the email you use for your account and I'll add some additional credits to your account.

**Comment by mmollick** [comment]
Oh and I've issued an updated package to packagist with a few small updates as well as the docblock updates you've made

**Comment by quentint** [comment]
Thanks, the examples look awesome!
Will integrate that on Monday, should be a breeze.
